### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by jessicaevans17** [jessicaevans17/assignments#37]
# Key areas of Information to include:

## Contact information
- [ ] Email
- [ ] Phone Number (Google numbers are great if you want to protect your personal number)
- [ ] Github link
- [ ] Portfolio link

## Summary
- [ ] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [ ] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [ ] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [ ] Write where you went college and your degree.
- [ ] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [ ] Upload or submit a link to your resume for review.

**Comment by jessicaevans17** [comment]
[Uploading JessicaEvansResume.pdf…]()

**Comment by ktrammell95** [comment]
Your resume still says uploading and I cannot open it to give feedback

**Comment by ktrammell95** [comment]
Just adding the file you sent me...

[JessicaEvansResume.pdf](https://github.com/jessicaevans17/assignments/files/3659593/JessicaEvansResume.pdf)

**Comment by ktrammell95** [comment]
I like the layout, very clean.

For your LinkedIn and GitHub you can shorten them by leaving out the starting and just use "jessicaevans17" or "jessica-marie-evans" if you have the label in front and use the same links

![Screen Shot 2019-09-26 at 3 36 58 PM](https://user-images.githubusercontent.com/10440779/65719583-184c6a00-e074-11e9-9f47-e2d4f1d00a3f.png)

You have a floating dot
![Screen Shot 2019-09-26 at 3 37 57 PM](https://user-images.githubusercontent.com/10440779/65719603-200c0e80-e074-11e9-8575-562cb40ad97c.png)

FYI you also don't have to give out your full address if you don't want to, just St. Petersburg, FL is enough. That is up to you.

**Comment by jessicaevans17** [comment]
Thanks, Katherine!
